### ISSUE TITLE
Extra newlines being inserted when using language server formatting

### ISSUE THREAD

**Issue by tapayne88** [tpope/vim-sleuth#80] opened 2022-02-23 20:16 UTC
Hi, I'm struggling with a problem where newlines are being inserted following a language server applying formatting. Please forgive my ignorance as my knowledge of this area of neovim / vim is pretty limited.

**Steps to reproduce**

My Neovim version
```
❯ nvim --version
NVIM v0.6.1
```

<details>
  <summary>Sample config</summary>

Sorry for the lua 🙂 
```lua
-- Pulled from telescope.nvim
-- https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
--
-- To make use of this file run the following
-- nvim -u ~/.config/nvim/minimal.lua ...
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
            'tpope/vim-sleuth', {
                'nvim-treesitter/nvim-treesitter',
                config = function()
                    require"nvim-treesitter.configs".setup {
                        ensure_installed = {"lua"},
                        highlight = {enable = true}
                    }
                end
            }, {
                'neovim/nvim-lspconfig', -- LSP server config
                requires = {"williamboman/nvim-lsp-installer"},
                config = function()
                    vim.lsp.set_log_level(vim.lsp.log_levels.DEBUG)

                    local lsp_installer = require "nvim-lsp-installer"

                    lsp_installer.settings({
                        install_root_dir = "/tmp/nvim/lsp_servers"
                    })

                    local name, version =
                        require"nvim-lsp-installer.servers".parse_server_identifier(
                            'sumneko_lua@v2.6.6')
                    local ok, server = lsp_installer.get_server(name)
                    if ok then
                        if not server:is_installed() then
                            server:install(version)
                        end
                        server:on_ready(function()
                            server:setup({
                                cmd = {"lua-language-server", "--preview"}
                            })
                        end)
                    end
                end
            }
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = {non_interactive = true}
        }
    }
end

_G.load_config = function()
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end

if vim.fn.isdirectory(install_path) == 0 then
    print("Installing packer packages...")
    vim.fn.system {
        'git', 'clone', '--depth=1',
        'https://github.com/wbthomason/packer.nvim', install_path
    }
end

load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```
</details>

1. Open a file of filetype with language server that supports formatting attached
2. Run `:lua vim.lsp.buf.formatting()` to trigger formatting
3. Observe no new extra line inserted
3. Open a second file of the same filetype
3. Run `:lua vim.lsp.buf.formatting()` to trigger formatting
4. Observe new extra line inserted

This recording hopefully shows what's happening (sorry about the size)
[![asciicast](https://asciinema.org/a/471208.svg)](https://asciinema.org/a/471208)

I've done a little git bisecting and it seem that https://github.com/tpope/vim-sleuth/commit/861707c50fba56ec9b8de02533b9b239ff589757 (and https://github.com/tpope/vim-sleuth/commit/ca8c4f04a3778c8278d607cb5bb430c5e9a17c39) are where I started seeing the issue.

From looking at the language server format response the text being set includes a `\n` character but prior to the above changes a blank newline never appeared.

My current workaround is to override each buffer's `fixendofline` option but I'm not sure I understand why the problem is occurring in the first place 😅 
```vim
au BufEnter * setlocal fixendofline
```

Any help / thoughts would be great, thanks!

**Comment by tpope** [comment] 2022-02-23 20:34
Can your try with sleuth.vim uninstalled, and with `:set nofixendofline` in your vimrc, and see if the issue still occurs?

**Comment by tapayne88** [comment] 2022-02-24 08:43
Hi Tim, thanks for your reply!

I've just tried this and I see the same erroneous new lines appear however they appear in the first file and not the second (files in asciinema clip).

I'm setting the value like this in the sample config
```lua
_G.load_config = function()
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    vim.cmd [[ set nofixendofline ]]
end
```

I guess perhaps the second file is receiving the default Neovim value to fix as using the below causes the issue across both buffers.
```lua
vim.cmd [[ au BufEnter * set nofixendofline ]]
```

**Comment by tpope** [comment] 2022-02-24 19:18
There are indeed quirks around global vs local options which I noticed trying (and failing) to reproduce the issue. To be super explicit, check all of `:verbose set fixendofline?`, `:verbose setglobal fixendofline?`, and `:verbose setlocal fixendofline?` in both the first and second buffer. I would expect all 6 cases to show `nofixendofline`, but the second buffer won't show the "Last set from" line in the cases where it's inheriting.

**Comment by tapayne88** [comment] 2022-02-25 13:35
> ```lua
> _G.load_config = function()
>     -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
>     vim.cmd [[ set nofixendofline ]]
> end
>
> ```

Firstly I think this config wasn't helpful as it wouldn't have been applied to the first file so I think you can ignore my last comment, sorry! Setting `vim.cmd[[ set nofixendofline ]]` on line 1 of the file should have the desired affect.

In answer to your question, this is what I found.

### With vim-sleuth

When I revert my config back to that of the sample config and this is what I found

| Bufnr | File        | `:verbose set fixendofline?` | `:verbose setglobal fixendofline?`                                                                                   | `:verbose setlocal fixendofline?` |
| ----- | ----------- | ---------------------------- | -------------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| 1     | `file1.lua` | `fixendofline`               | `nofixendofline`<br />`Last set from /private/tmp/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 513` | `fixendofline`                    |
| 2     | `file2.lua` | `nofixendofline`             | `nofixendofline`<br />`Last set from /private/tmp/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 513` | `nofixendofline`                  |

### Without vim-sleuth

With vim-sleuth omitted and `vim.cmd[[ set nofixendofline ]]` as line 1 of the sample config I find the following

| Bufnr | File        | `:verbose set fixendofline?`                            | `:verbose setglobal fixendofline?`                      | `:verbose setlocal fixendofline?`                       |
| ----- | ----------- | ------------------------------------------------------- | ------------------------------------------------------- | ------------------------------------------------------- |
| 1     | `file1.lua` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` |
| 2     | `file2.lua` | `nofixendofline`                                        | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`                                        |

As I found with the autocommand, with the config correctly set this now appears to add new lines to all buffers.

### With autocommand

With vim-sleuth omitted and `vim.cmd [[au BufEnter * set nofixendofline]]` as line 1 of the sample config I find the following

| Bufnr | File        | `:verbose set fixendofline?`                            | `:verbose setglobal fixendofline?`                      | `:verbose setlocal fixendofline?`                       |
| ----- | ----------- | ------------------------------------------------------- | ------------------------------------------------------- | ------------------------------------------------------- |
| 1     | `file1.lua` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` |
| 2     | `file2.lua` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` | `nofixendofline`<br />`Last set from anonymous :source` |

As before the new lines now appear in all buffers.

Hope this is helpful!

**Comment by tpope** [comment] 2022-02-26 07:52
So Sleuth's use of `:setglobal nofixendofline` causes that first buffer quirk that I'll need to fix. But the primary issue, with the blank line being added, appears to be solely a bug in the way Neovim's LSP formatter interacts with `'fixendofline'`. Or at least that would be my conclusion if I could actually reproduce it. Is there perhaps another factor, such as the choice of LSP, that is a necessary precondition? I'm testing with the TypeScript one.

**Comment by tapayne88** [comment] 2022-02-27 10:16
> appears to be solely a bug in the way Neovim's LSP formatter interacts with 'fixendofline'

Afraid I can't comment on that but I have reproduced the issue using a few language servers, namely [rnix-lsp](https://github.com/nix-community/rnix-lsp), prettier (via [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver)) and [lua](https://github.com/sumneko/vscode-lua).

> I'm testing with the TypeScript one.

To my knowledge the TypeScript language server doesn't support formatting, but I may be wrong on that!

I have done a little digging around to see if anyone else is seeing the issue but am yet to find anything. Given there are quite a few people playing around with Neovim LSP I'd have thought others would be reporting it if it were in neovim's handling, but this is an assumption.

**Comment by tpope** [comment] 2022-02-27 10:54
You reproduced it yourself, without Sleuth and with `:set nofixendofline`. Ergo, the issue does not involve Sleuth, it's between the Neovim LSP formatter and `nofixendofline`.

**Comment by tapayne88** [comment] 2022-02-27 11:38
This is true! I guess I'm not too clear on what `fixendofline` does and why it's needed when working with LSP formatters.

Do you think it would be possible / make sense to make it configurable?

**Comment by tpope** [comment] 2022-02-27 15:36
https://github.com/neovim/neovim/blob/5b839ced692230fe582fde41f79f875ee90451e8/runtime/lua/vim/lsp/util.lua#L479-L485

Can you try removing this from your Neovim install and see if that fixes it?

**Comment by tpope** [comment] 2022-02-27 15:39
Also try with deleting just the line that references `fixeol`.

**Comment by tapayne88** [comment] 2022-02-28 19:30
> https://github.com/neovim/neovim/blob/5b839ced692230fe582fde41f79f875ee90451e8/runtime/lua/vim/lsp/util.lua#L479-L485
> 
> Can you try removing this from your Neovim install and see if that fixes it?

With all these lines removed the issue still occurs.

> Also try with deleting just the line that references `fixeol`.

Removing [this line](https://github.com/neovim/neovim/blob/5b839ced692230fe582fde41f79f875ee90451e8/runtime/lua/vim/lsp/util.lua#L481) looks to fix it.

**Comment by tpope** [comment] 2022-03-01 01:27
Great, that's the problem. tl;dr it's only checking `'fixeol'` when it should also be checking `'eol'`. Can you try adding _this_ line and keeping everything else the same and verify that also fixes it?

```lua
fix_eol = fix_eol and not api.nvim_buf_get_option(bufnr, 'eol')
```

After I get a PR in to fix that I'll circle back on the workaround.

**Comment by tapayne88** [comment] 2022-03-01 18:41
It doesn't seem to be working 😟 

Using the sample config I now see it introducing new lines on both the first and second buffers.

This is how the end of the modified function looks
```lua
  -- Remove final line if needed
  local fix_eol = has_eol_text_edit
  fix_eol = fix_eol and api.nvim_buf_get_option(bufnr, 'fixeol')
  fix_eol = fix_eol and (vim.api.nvim_buf_get_lines(bufnr, -2, -1, false)[1] or '') == ''
  fix_eol = fix_eol and not api.nvim_buf_get_option(bufnr, 'eol')
  if fix_eol then
    vim.api.nvim_buf_set_lines(bufnr, -2, -1, false, {})
  end
```

**Comment by tpope** [comment] 2022-03-01 19:55
Not to fret, I just butchered the Boolean logic. Can you try swapping in this line for the `fixeol` line?

```lua
fix_eol = fix_eol and (api.nvim_buf_get_option(bufnr, 'fixeol') or api.nvim_buf_get_option(bufnr, 'eol'))
```

(I could figure this out in 2 minutes if I could actually reproduce. If you can find an LSP that can reproduce this that isn't a massive pain to install let me know.)

**Comment by tapayne88** [comment] 2022-03-01 23:13
> ```lua
> fix_eol = fix_eol and (api.nvim_buf_get_option(bufnr, 'fixeol') or api.nvim_buf_get_option(bufnr, 'eol'))
> ```

That looks to have got it!

> (I could figure this out in 2 minutes if I could actually reproduce. If you can find an LSP that can reproduce this that isn't a massive pain to install let me know.)

Does the sample `init.lua` not work for you?

**Comment by tpope** [comment] 2022-03-02 10:45
PR submitted.

> Does the sample `init.lua` not work for you?

The sample `init.lua` doesn't demonstrate the problem as it doesn't  enable any LSPs. `:lua vim.lsp.buf.formatting()` is a no-op with it.

**Comment by tapayne88** [comment] 2022-03-02 12:02
> PR submitted.

Awesome, thanks so much for your help @tpope!

> The sample `init.lua` doesn't demonstrate the problem as it doesn't enable any LSPs. `:lua vim.lsp.buf.formatting()` is a no-op with it.

Huh, it _should_ as I've included [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) and configured lua language server to install. You should be able to run `:LspInstallInfo` to see it trying to install (or failing to 🙂) - might take a few seconds

**Comment by tpope** [comment] 2022-03-02 19:14
Ah, I missed the collapsed section and assumed you were referring to one of the shorter snippets. I guess it's moot now.

I do think it makes sense to change my approach here, but I'm still noodling over what form that should take. Will close this issue once that's done.

**Comment by tpope** [comment] 2022-03-02 19:16
And for posterity, the reason Sleuth touches this option at all is for `insert_final_newline = false` in `.editorconfig`.

**Comment by mjlbach** [comment] 2022-03-02 19:50
Neovim 0.7 should release soon-ish (next 2 months) with the fix, otherwise you can use the nightly. Thanks for the fix!

**Comment by tpope** [comment] 2022-03-02 20:17
Two months is good to hear. The fact `'fixendofline'` is local and not "global-local" like I had assumed means I need to move away from my `setglobal` approach regardless.

**Closed** 2022-03-04 15:18 UTC
