### ISSUE TITLE
Option to disable EditorConfig override?

### ISSUE THREAD

**Issue by jackielii** [tpope/vim-sleuth#83] opened 2022-06-14 21:04 UTC
This feels like an unfortunate situation:

I have a Go project with no modeline or editor config. I use default `sw` which is `4`.

I use LSP go to definition to jump around and end up in something like `/opt/homebrew/Cellar/go/1.18.3/libexec/src/fmt/print.go`. Then the `sw` suddenly becomes `2`. `:verbose Sleuth` tells me:

```
:setlocal expandtab             " from /opt/homebrew/.editorconfig line 8
:setlocal shiftwidth=2          " from /opt/homebrew/.editorconfig line 9
:setlocal fixendofline          " from /opt/homebrew/.editorconfig line 10
:setlocal endofline             " from /opt/homebrew/.editorconfig line 10
:setlocal fileformat=unix       " from /opt/homebrew/.editorconfig line 7
:setlocal fileencoding=utf-8    " from /opt/homebrew/.editorconfig line 6
:setlocal nobomb                " from /opt/homebrew/.editorconfig line 6
```

To Sleuth, it's definitely working as expected. But not sure I ever want this as everything in my homebrew packages will respect the homebrew's root `.editorconfig`.

This would normally be fine as I'll never edit these files. But since I have the indent line on, things look very strange. I always have to pause and think if something is wrong.

Maybe an option to disable the EditorConfig? Or exclude folder? The latter feels heavy...

**Comment by jackielii** [comment] 2022-06-14 21:12
Found this undocumented option:

```vim
let g:sleuth_editorconfig_overrides = {
    \ expand('$HOMEBREW_PREFIX/.editorconfig'): '',
    \ }
```

**Comment by andrewferrier** [comment] 2023-01-06 16:27
I think there is a related challenge here with NeoVim. @tpope, I'm not sure if you consider NeoVim a supported user of this plugin (although I use and have been using it regularly together over the last few years). NeoVim has fairly recently merged built-in editorconfig support: https://github.com/neovim/neovim/pull/21633. It would be really nice to be able to disable the editorconfig capabilities of vim-sleuth, whilst retaining its heuristics (which are super-useful in the 80% case where editorconfig is not yet used for a project).

**Comment by tpope** [comment] 2023-01-06 18:21
Disabling EditorConfig in Sleuth would cause it to apply heuristics even when a relevant EditorConfig rule exists. Depending on autocommand order this could even cause Sleuth's heuristics to _override_ Neovim's built-in EditorConfig support. Whereas now, the worst case scenario is settings get applied twice. Am I missing something?

**Closed by tpope** 2023-01-06 18:21 UTC

**Comment by gpanders** [comment] 2023-01-06 23:17
@andrewferrier Alternatively, disable Neovim's builtin EditorConfig support in favor of vim-sleuth's (pending https://github.com/neovim/neovim/pull/21649):

```vim
let g:editorconfig = v:false
```

**Comment by andrewferrier** [comment] 2023-01-09 11:29
@tpope it's a fair point, current worst case is actually better. Let's stick with what you have.

@gpanders thanks, wasn't aware of that PR.

**Comment by wickles** [comment] 2023-10-02 19:42
> Found this undocumented option:
> 
> ```viml
> let g:sleuth_editorconfig_overrides = {
>     \ expand('$HOMEBREW_PREFIX/.editorconfig'): '',
>     \ }
> ```

I don't think this option supports what I want to do. I want to override editorconfig but only in `.git` data directories, since I often edit `.git/config` directly which should always use tabs.

**Comment by tpope** [comment] 2023-10-02 23:56
> I don't think this option supports what I want to do. I want to override editorconfig but only in `.git` data directories, since I often edit `.git/config` directly which should always use tabs.

It doesn't do what you want to do, but it solves the problem you're trying to solve. Namely the problem is using `*`:

```
[*]
indent_style = space
```

There's a difference between "this project uses spaces for indentation" and "every file in every subdirectory of this directory should use spaces instead of tabs". Personally, any time I see `*`, I want to throw the `.editorconfig` out and start over. Hence the design of the option.

For what you _want_ to do, there's no built-in solution, but it should be straightforward to achieve by sticking a `root = true` EditorConfig in a [Git init template](https://git-scm.com/docs/git-init#_template_directory).

> Git data directories are not part of the repository so should never be influenced by editorconfig anyway.

Citation needed. I don't see anything in the [EditorConfig spec](https://spec.editorconfig.org/) about that. In fact, [some usages](https://github.com/git/git/blob/d0e8084c65cbf949038ae4cc344ac2c2efd77415/.editorconfig#L15-L16) of EditorConfig assume you _do_ want it to influence `.git`.

**Comment by wickles** [comment] 2023-10-04 02:35
You're right, and I agree about `*`.

> For what you _want_ to do, there's no built-in solution, but it should be straightforward to achieve by sticking a `root = true` EditorConfig in a [Git init template](https://git-scm.com/docs/git-init#_template_directory).

Interesting idea! I suppose I can add that to my existing clones as well. Thanks.

**Comment by tpope** [comment] 2023-10-04 15:51
> You're right, and I agree about `*`. Like OP my problem is also related to nested repositories in homebrew. Maybe I will see if I can get this changed over there.

Oh please do. That will help a lot more than just Sleuth users. I think the ideal fix there would be to target not (just?) file extensions but the containing directories. The `.gitignore` opts *in* certain paths, and I think the `.editorconfig` should mirror that, though it doesn't need to be quite so granular.
